// examples/test.vue
<template>
  <div v-on:click="handle">
    {{ 'jack' }} - {{ num }}

    <a href="http://www.baidu.com" target="_blank"> baidu </a>

    <span v-for="i in 7"> {{ 'jack' }} - {{ i }} </span>
  </div>
</template>

<script>
export default {
  name: 'app',
  components: {},
  props: {},
  data: {
    num: 1,
  },
  watch: {},
  computed: {},
  created() {},
  mounted() {},
  methods: {
    handle() {
      this.num++
    },
  },
}
</script>

<style scoped lang="scss">
.lowerCamelCase {
  color: #ffffff;
  font-size: 12px;
  background: url(https://www.matrixtheone.ga/images/Wives/BingBing-1.webp);
}
a {
  display: inline;
  width: 100px;
}
@for $i from 1 through 4 {
  .item-#{$i} {
    width: 2em * $i;
  }
}
</style>

// examples/test.jsx
import React, { useState } from 'react'
import { useEffect } from 'react'

const App = () => {
  const [num, setNum] = useState(1)

  return (
    <div onClick={() => setNum(num + 1)}>
      {'jack'} - {num}

      <a href='http://www.baidu.com' target='_blank'>
        baidu
      </a>

      {[1, 2].map(i => (
        <span>{i}</span>
      ))}
    </div>
  )
}

export default App
